// Code generated by protoc-gen-go.                                                                                                                                                                                                                                                 
// source: fake.proto                                                                                                                                                                                                                                                               
// DO NOT EDIT!                                                                                                                                                                                                                                                                     

package fake

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google/api"
import google_api5 "google/api"
import google_protobuf5 "google/protobuf"

import (
        context "golang.org/x/net/context"
        grpc "google.golang.org/grpc"
)
