# Copyright 2016 Google Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Tasks related to generation of GAPIC wrappers"""

import os

from pipeline.tasks import task_base


class BatchOutputDirTask(task_base.TaskBase):
    """Output the code gen dir as batch_code_dir
    """
    default_provides = ['batch_code_dir', 'batch_lang_api_dir']

    def execute(self, language, api_name, gapic_code_dir, batch_output_dir):
        return [gapic_code_dir,
                os.path.join(batch_output_dir, language, api_name)]


class BatchCleanTask(task_base.TaskBase):
    """Delete all of the files in the batch_lang_api_dir.
    """

    def execute(self, batch_lang_api_dir):
        self.exec_command(['rm', '-rf', batch_lang_api_dir])


class BatchCopyTask(task_base.TaskBase):
    """Copy the files generated by Gapic toolkit to the batch_lang_api_dir
    """

    def execute(self, language, api_name, batch_lang_api_dir,
                batch_code_dir):
        print 'Copying', batch_code_dir + '/* to', batch_lang_api_dir
        self.exec_command(['mkdir', '-p', batch_lang_api_dir])
        for entry in os.listdir(batch_code_dir):
            src_path = os.path.join(batch_code_dir, entry)
            self.exec_command([
                'cp', '-rf', src_path, batch_lang_api_dir])
