#!/bin/bash
# A fake stand-in for packman for pipeline testing

main() {
  local _out_dir=""
  local _pwd=$(pwd)

  # Compute output directory (by -o option)
  _out_dir=$(echo $@ | sed -n 's/.*-o \([^[:space:]]*\).*/\1/p')

  if [ ! -z "$_out_dir" ]; then
    mkdir -p $_out_dir
    echo "gen-api-package called with args: $@" >> "$_out_dir/gen-api-package_out.txt"
  fi
}

main $@
