#!/bin/bash
# A fake stand-in for protoc for pipeline testing

main() {

  local _out_dir=""

  # If available, output specified by `-o`
  _out_dir=$(echo $@ | sed -n 's/.*-o \([^[:space:]]*\).*/\1/p')

  # Otherwise `--grpc_out`
  if [ -z "$_out_dir" ]; then
    _out_dir=$(echo $@ | sed -n 's/.*--grpc_out=\([^[:space:]]*\).*/\1/p')
  fi

  if [ ! -z "$_out_dir" ]; then
    mkdir -p $_out_dir
    echo "protoc invoked with args: $@" >> "$_out_dir/protoc_out.txt"
  fi
}

main $@
