#!/bin/bash
# A fake stand-in for yapf for pipeline testing

main() {
  local _out_dir=""
  local _pwd=$(pwd)

  # Compute output directory (by -o option)
  _out_dir=$( dirname ${@: -1} )

  if [ ! -z "$_out_dir" ] && [ "$_out_dir" != "." ]; then
    mkdir -p $_out_dir
    echo "yapf called with args: $@" >> "$_out_dir/yapf_out.txt"
  fi
}

main $@
